---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elastic
  description: Elasticssearch for app
spec:
  type: database
  owner: nova
  system: nova
  domain: nova
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cache
  description: Redis for app
spec:
  type: database
  owner: nova
  system: nova
  domain: nova
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: storage
  description: Storage for app
spec:
  type: database
  owner: nova
  system: nova
  domain: nova
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: serviceBus
  description: Queue for app
spec:
  type: database
  owner: nova
  system: nova
  domain: nova
