---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elastic
  description: Elasticssearch for app
spec:
  type: database
  owner: nova
  system: nova
  domain: nova
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: keyvault
  description: keyvault for app
spec:
  type: vault
  owner: nova
  system: nova
  domain: nova
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: storage
  description: Storage for app
spec:
  type: storage
  owner: nova
  system: nova
  domain: nova
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: blobStorage
  description: Storage for app
spec:
  type: storage
  owner: nova
  system: nova
  domain: nova
  dependsOn:
    - resource:storage
