---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [jdoe]
# # https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
# apiVersion: backstage.io/v1alpha1
# kind: User
# metadata:
#   name: guest
# spec:
#   memberOf: [guests]
# ---
# # https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: guests
# spec:
#   type: team
#   children: []
