---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: tomelin
  domain: payments

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  #namespace: default
  name: tomelin
relations:
  - type: hasMember
    targetRef: user:default/guest
    target:
      kind: user
      namespace: default
      name: guest
  - type: ownerOf
    targetRef: api:default/example-grpc-api
    target:
      kind: api
      namespace: default
      name: example-grpc-api
  - type: ownerOf
    targetRef: component:default/example-website
    target:
      kind: component
      namespace: default
      name: example-website
  - type: ownerOf
    targetRef: system:default/examples
    target:
      kind: system
      namespace: default
      name: examples
spec:
  type: team
  children: []