apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: my-custom4-template
  title: we custom4 Template
  description: An we template for the scaffolder that creates a simple custom4 service
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: custom4 fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: we custom4 name for the component
          ui:field: MyCustomExtension
